[package]
name = "gir2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmlserde = "0.7"
xmlserde_derives = "0.7"