[workspace]
resolver = "2"
members = [
    "codegen",
    "parser"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
parser = {package = "gir-parser", path ="./parser"}
