[package]
name = "gir-config"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.4.6", features = [ "cargo", "derive" ] }
parser.workspace = true
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
toml = "0.8"
tracing = "0.1"
